Repository Namanl2001/MERN-Gurujii-dev, pull requests merged in 2021-05, with the labels that each got.

#171 Update README.md
  README.md
Labels: GSSOC21, Level0

#167 Header is fixed
  src/components/E404.jsx
  src/components/home.jsx
  src/components/navbar.jsx
  src/components/style.css
Labels: GSSOC21, Level2

#175 Improved Form Responsiveness
  src/App.css
  src/components/form.jsx
  src/components/style.css
Labels: GSSOC21, Level2

#180 our reach
  src/assets/calendar.png
  src/assets/leadership.png
  src/assets/student.png
  src/components/Reach.jsx
  src/components/home.jsx
  src/components/style.css
Labels: GSSOC21, Level2

#168 card alignment
  src/components/card.jsx
  src/components/style.css
Labels: GSSOC21, Level1

#179 Added home/external tutor filter
  package.json
  src/components/filter.jsx
  src/store/reducer/user.js
  yarn.lock
Labels: GSSOC21, Level2

#184 Remove commented code.
  src/store/reducer/user.js
Labels: GSSOC21, Level2

#191 scroll bar
  src/App.css
Labels: GSSOC21, Level1

#185 splash screen
  src/App.js
  src/components/Preloader.jsx
  src/components/style.css
Labels: GSSOC21, Level2

#192 our vision
  src/assets/01.png
  src/assets/02.png
  src/assets/03.png
  src/components/home.jsx
  src/components/ourvision.jsx
  src/components/style.css
Labels: GSSOC21, Level2

#195 social media sidebar added
  package.json
  src/components/home.jsx
  src/components/style.css
  yarn.lock
Labels: GSSOC21, Level2

#197 Code splitting
  src/App.js
Labels: GSSOC21, Level2

#198 added admin middleware
  backend/controllers/user.controller.js
  backend/middleware/admin.js
  backend/models/user.model.js
  package.json
  yarn.lock
Labels: GSSOC21, Level1

#203 Seperatecomponent
  src/components/Sidebar.jsx
  src/components/filter.jsx
  src/components/home.jsx
  src/components/style.css
Labels: GSSOC21, Level2

#207 Speech Feature In ChatBot
  src/components/chatbot.jsx
Labels: GSSOC21, Level1

#209 admin feature added
  backend/controllers/admin.controller.js
  backend/routes/admin.js
  backend/server.js
  package.json
  yarn.lock
Labels: GSSOC21, Level2

#208 Added an about page
  package.json
  src/App.js
  src/components/Reach.jsx
  src/components/about.jsx
  src/components/contributors.jsx
  src/components/home.jsx
  src/components/navbar.jsx
  src/components/ourvision.jsx
  src/components/style.css
  yarn.lock
Labels: GSSOC21, Level3

#220 Name Filter
  package.json
  src/store/reducer/user.js
  yarn.lock
Labels: GSSOC21, Level3

#223 fixed update profile
  backend/controllers/user.controller.js
  backend/models/user.model.js
Labels: GSSOC21, Level2

#151 Profilepic
  README.md
  backend/.gitignore
  backend/controllers/user.controller.js
  backend/models/user.model.js
  backend/package.json
  backend/public/uploads/photo.png
  backend/routes/users.js
  backend/yarn.lock
  public/photo.png
  src/components/card.jsx
  src/components/form.jsx
  src/components/style.css
Labels: GSSOC21, Level3

#225 auto messege on pr
  .github/workflows/automessege_on_pr.yml
Labels: GSSOC21, Level2
