Repository Namanl2001/MERN-Gurujii-dev, pull requests merged in 2021-04, with the labels that each got.

#124 updated readme
  README.md
Labels: GSSOC21, Level0

#137 Ms. option added
  src/components/form.jsx
  src/components/update.jsx
Labels: GSSOC21, Level0

#125 Auto Labelling Bot
  .github/workflows/issue_label.yml
Labels: GSSOC21, Level1

#142 flip card changes made
  src/components/card.jsx
  src/components/style.css
Labels: GSSOC21, Level2

#146 Removed body-parser
  README.md
  backend/server.js
Labels: GSSOC21, Level1

#150 Grammatical errors corrected
  README.md
Labels: GSSOC21, Level0

#141 improved UI
  backend/.gitignore
  backend/package.json
  src/components/card.jsx
  src/components/filter.jsx
  src/components/style.css
Labels: GSSOC21, Level1

#154 Setup Github Actions for Prettier and Linting #153 Fix
  .github/workflows/linter.yml
Labels: GSSOC21, Level1

#157 Removed the modal close button
  src/components/navbar.jsx
Labels: GSSOC21, Level1

#18 Refactoring duplicate code
  src/components/form.jsx
  src/components/navbar.jsx
  src/components/update.jsx
  src/store/reducer/user.js
Labels: GSSOC21, Level3

#162 name filter added
  src/App.css
  src/components/card.jsx
  src/components/filter.jsx
  src/components/form.jsx
  src/components/style.css
  src/components/update.jsx
  src/store/reducer/user.js
Labels: GSSOC21, Level3

#159 404 page added
  src/App.js
  src/assets/404.png
  src/assets/board.jpg
  src/components/E404.jsx
  src/components/alert.jsx
  src/components/filter.jsx
  src/components/home.jsx
  src/components/navbar.jsx
  src/components/style.css
Labels: GSSOC21, Level2
