Repository Namanl2001/MERN-Gurujii-dev, pull requests merged in 2021-03, with the labels that each got.

#30 Added a pull request template
  .github/pull_request_template.md
Labels: GSSOC21, level: 1

#25 Doc fixes nikita
  README.md
Labels: GSSOC21, Level1

#44 Added issue templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: GSSOC21, Level1

#19 Add Contributing.md
  contributing.md
Labels: GSSOC21, Level1

#48 Added Concurrently Dependency to Project
  package.json
  yarn.lock
Labels: GSSOC21, Level2

#46 Added Website Gif
  README.md
Labels: GSSOC21, Level0

#43 Added Pointer Cursor Property for Dropdown items
  src/App.css
Labels: GSSOC21, Level1

#32 Randomizatin add to the Profile
  src/components/home.jsx
Labels: GSSOC21, Level2

#47 Dialog box delete
  public/index.html
  src/components/navbar.jsx
  src/components/style.css
Labels: GSSOC21, Level2

#65 Updating Backend README.md
  backend/README.md
Labels: GSSOC21, Level0

#54 Resolved conflicts and updated readme
  README.md
Labels: GSSOC21, Level0

#50 Title
  backend/models/user.model.js
  backend/routes/users.js
  src/components/card.jsx
  src/components/form.jsx
  src/components/update.jsx
Labels: GSSOC21, Level2

#56 Fixed Issue #33 : Added a Scroll to top Button
  package.json
  src/App.css
  src/components/home.jsx
  src/components/scrollToTop.jsx
  yarn.lock
Labels: GSSOC21, Level2

#74 RE: Auto Format Code Issue #67 Fix #68
  .prettierignore
  .prettierrc.json
  package.json
  src/App.css
  src/App.js
  src/components/card.jsx
  src/components/filter.jsx
  src/components/form.jsx
  src/components/home.jsx
  src/components/login.jsx
  src/components/logout.jsx
  src/components/navbar.jsx
  src/components/scrollToTop.jsx
  src/components/style.css
  src/components/update.jsx
  src/index.css
  src/index.js
  src/store/reducer/user.js
  yarn.lock
Labels: GSSOC21, Level2

#77 body-parser removed and changes made to server.js
  backend/server.js
Labels: GSSOC21, Level2

#61 Auto closable alert
  src/components/navbar.jsx
  src/components/style.css
Labels: GSSOC21, Level2

#87 promises handled successfully and config folder created for database connection
  backend/config/db.js
  backend/server.js
Labels: GSSOC21, Level2

#91 Added config.example.js and instructions to run the server locally
  README.md
  backend/config.example.js
  backend/controllers/user.controller.js
  backend/routes/users.js
Labels: GSSOC21, Level2

#79 Added various security features issue #76
  backend/package-lock.json
  backend/package.json
  backend/server.js
  backend/yarn.lock
Labels: GSSOC21, Level2

#93 added gif
  README.md
  readme_assets/guruji_gif(1).gif
Labels: GSSOC21, Level2

#84 added footer
  src/App.js
  src/components/Footer.js
  src/components/style.css
Labels: GSSOC21, Level2

#95 Double Form Added
  backend/controllers/user.controller.js
  backend/package-lock.json
  backend/yarn.lock
  src/App.css
  src/components/form.jsx
  src/components/update.jsx
  yarn.lock
Labels: GSSOC21, Level2

#104 removes default value on expanding any dropdown
  src/components/form.jsx
  src/components/update.jsx
Labels: GSSOC21, Level2

#92 Added favicon
  public/faviconNew.png
  public/index.html
Labels: GSSOC21, Level0

#103 Tutorty
  backend/controllers/user.controller.js
  backend/models/user.model.js
  src/App.css
  src/components/card.jsx
  src/components/form.jsx
  src/components/update.jsx
Labels: GSSOC21, Level2

#106 removed arrows and added constraints for filter input
  src/App.css
  src/components/filter.jsx
Labels: GSSOC21, Level1

#109 Added a chatbot #75 Fix
  package.json
  src/App.js
  src/components/chatbot.jsx
  yarn.lock
Labels: GSSOC21, Level2

#116 added sir/madam in chatbox. Fixes #115
  src/components/chatbot.jsx
Labels: GSSOC21, Level0

#117 Newfooter
  src/components/Footer.js
  src/components/Footer.jsx
  src/components/home.jsx
  src/components/scrollToTop.jsx
  src/components/style.css
Labels: GSSOC21, Level2
